version: "3.9"

services:
  app:
    image: mathesar/mathesar-prod:latest
    restart: always
    environment:
      ALLOWED_HOSTS: "*"
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      MATHESAR_DATABASES: ${DATABASES_MANAGEMENT}
    volumes:
      - ${BASE_VOLUME}/mathesar/static:/code/static
      - ${BASE_VOLUME}/mathesar/media:/code/media
    networks:
      - internal
      - db-management
      - nginx
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
    healthcheck:
      test: curl -f http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_APP_CPU:-1}
          memory: ${LIMIT_APP_RAM:-256M}
        reservations:
          cpus: "0.1"
          memory: 16M
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - 5432
    volumes:
      - ${BASE_VOLUME}/db:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_DB_CPU:-1}
          memory: ${LIMIT_DB_RAM:-256M}
        reservations:
          cpus: "0.1"
          memory: 16M
  db-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: always
    environment:
      DATA_SOURCE_NAME: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    expose:
      - 9187
    networks:
      - internal
      - monitoring
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: ${LIMIT_CPU_DB_EXPORTER:-0.2}
          memory: ${LIMIT_RAM_DB_EXPORTER:-128M}
        reservations:
          cpus: "0.1"
          memory: 10M

networks:
  internal:
  nginx:
    external: true
  db-management:
    external: true
  monitoring:
    external: true
